// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tv-maintenance/Efir.tsx": () => import("../components/mockups/tv-maintenance/Efir.tsx"),
  "./components/mockups/tv-maintenance/Minimalizm.tsx": () => import("../components/mockups/tv-maintenance/Minimalizm.tsx"),
  "./components/mockups/tv-maintenance/Signal.tsx": () => import("../components/mockups/tv-maintenance/Signal.tsx")
};
